### PR TITLE
adds `--config` option to inline overrides

### PR DESCRIPTION
**Pull request by nsfmc**
This allows a user to supply an absolute path to an ini-formatted config
file that isn't one of the standard `.flake8`, `setup.cfg` or `tox.ini`

usage in project settings:
```json
{
	"SublimeLinter": {
		"linters": {
			"flake8": {
				"config": "/path/to/some/config.ini"
			}
		}
	}
}
```

i'm not sure if this is generally useful, but my case, my main work project keeps its config in a nonstandard path so i'm using this forked version to get linting working but if there's a better approach, i'm all game.

### CODE REVIEW

**Comment by kaste** [comment]
Q: Can't you just use the `args` setting? Or is that broken?

**Comment by nsfmc** [comment]
sorry was out of town. that 100% works as well, but it feels like a weird approach for what is a common operation. i guess this is more of an issue with sublimelinter, since it's unclear to me which things should be elevated to config options and which should be relegated to `args`. 

in any case, please feel free to close this if it's not needed.

hope alls well

**Comment by braver** [comment]
> since it's unclear to me which things should be elevated to config options and which should be relegated to args

I don’t see how there is any need at all to take on the maintenance burden of mapping *any* args to config options? I would never advise plugin authors to do so, but we have a lot of design choices like that that provide very little tangible value.

I would similarly advice against adding inline settings for this situation. Project settings, or sublimelinterrc, seem much more appropriate for something that isn’t specific to a single file. And again, args already supports this.

**Comment by kaste** [comment]
Vote for close as well.

We should promote usage of __args__

**Comment by braver** [comment]
> We should promote usage of args

💯

**Comment by nsfmc** [comment]
Thanks both for the thoughtful replies, please feel free to close, I just suspected that nonstandard names and placed team-based config files were a common enough project level setting to warrant a top level prefs flag as described in the pr.

That said, I’ll be happy to use args if that is the preferred approach

**Comment by braver** [comment]
> I’ll be happy to use args if that is the preferred approach

Yeah, I’m a bit on a crusade to reduce the number of ways the same thing can be achieved in SublimeLinter, the cruft is getting in the way. Good to hear there is a way for you to get it set up right though.

**Pull request closed without merging**
