### PR TITLE
Reposition white-space errors

### PR DESCRIPTION
**Pull request by kaste**
Let's see if this is 🌶  or 💩

### CODE REVIEW

**Comment by braver** [comment]
This doesn't work for me, and with the recent solution for outlines on whitespace errors shouldn't be necessary anymore right?

**Comment by kaste** [comment]
This works against current SublimeLinter master. 

image


image


image


image

**Comment by braver** [comment]
Weird, I get this:

```
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 201, in await_futures
    yield future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 96, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 935, in lint
    error = self.process_match(m, vv)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1011, in process_match
    line, start, end = self.reposition_match(m.line, col, m, vv)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-flake8/linter.py", line 112, in reposition_match
    return (line - (count - 1), 0, count - 1)
UnboundLocalError: local variable 'count' referenced before assignment
```

**Comment by kaste** [comment]
Ok, fixed the indentation error. Obviously your E303 does not match my regex `match = re.match('E303 too many blank lines \((\d+)', m.message)`

**Comment by kaste** [comment]
Ah, okay, bc you removed `show_code` m.message doesn't contain the code anymore. Fixed.

**Comment by braver** [comment]
Ok, it works now. To me this is cool but not necessary. So, if you want it that's ok.

**Comment by FichteFoll** [comment]
The idea is to highlight the whitespace that causes the error instead of the first word on the line, correct? If so, this is :hot_pepper:

**Comment by kaste** [comment]
Ty.

**Comment by braver** [comment]
@kaste I force-pushed the sl4 branch to master, the old master is now sl3. Removing the sl4 branch closed this PR.

Wanna merge this? I think it'll work really well with the new demote-while-editing stuff.

**Pull request merged**
