### PR TITLE
Filter paths

### PR DESCRIPTION
**Pull request by gerardroche**
Expand home directory placeholders and other environment variables.

See:

* https://docs.python.org/3/library/os.path.html#os.path.expanduser
* https://docs.python.org/3/library/os.path.html#os.path.expandvars

Relates to:

* https://github.com/SublimeLinter/SublimeLinter3/issues/556.

### CODE REVIEW

**Comment by kaste** [comment]
I'm generally :+1: 

`expand_variables` is used https://github.com/SublimeLinter/SublimeLinter-flake8/blob/4dbc888e7023b4a6667e7b453c12cf30befbb6b6/linter.py#L58 and https://github.com/SublimeLinter/SublimeLinter-flake8/blob/4dbc888e7023b4a6667e7b453c12cf30befbb6b6/linter.py#L84

Any specific reason, you patch only the first one?

Otherwise, since the fn `expand_variables` is already present and in the right module `util`. Why not patch it over there.

As usual, probably leave the whitespace alone. 😄

**Comment by gerardroche** [comment]
`expand_variables` isn't doing what you probably think it is. 

It doesn't expand `~` or environment variables and will mangle some of them, which is why in the PR I run the path through `filter_path()` before expanding ST variables. 

```
print('1:', util.expand_variables('~/path'))
print('2:', util.expand_variables('${home}/path'))
print('3:', util.expand_variables('${HOME}/path'))
print('4:', util.expand_variables('${PROJECTS_PATH}/path'))
print('5:', util.expand_variables('${FOOBAR}/path'))
```

Expands to:

```
1: ~/path
2: /path
3: /path
4: /path
5: /path
```

`expand_variables()` also doesn't work if the file is not a real file on disk.

There are some other issues too. 

The `filter_path()` function will expand home directory variables and placeholders like `~` properly and for all os's and will also expand all environment variables properly. Unknown variables will be left as-is so after the path is run through the filter it can be safely run through ST `expand_variables()`.

**Comment by kaste** [comment]
I ask you to patch util.expand_variables(), unless you have specific reason you don't want that behavior for line 84. 

Otherwise, don't mess with the WS, t.i. don't delete empty lines all over the place.

Should we avoid sublime.expand_variables altogether? Or fix it?

**Comment by gerardroche** [comment]
> I ask you to patch util.expand_variables(), unless you have specific reason you don't want that behavior for line 84.

Done.

> Otherwise, don't mess with the WS, t.i. don't delete empty lines all over the place.

These are actually flake8 fixes. I opened a issue on the main SL repository with the same issue. I've removed these changes and leave to yourself.

```
$ flake8 --version
3.5.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.5.3 on Linux
$ flake8
./linter.py:45:1: D202 No blank lines allowed after function docstring
./linter.py:217:1: D202 No blank lines allowed after function docstring
./util.py:40:1: D202 No blank lines allowed after function docstring
./util.py:49:1: D202 No blank lines allowed after function docstring
./util.py:62:1: D202 No blank lines allowed after function docstring
./util.py:77:1: D202 No blank lines allowed after function docstring
./util.py:115:1: D202 No blank lines allowed after function docstring
./util.py:128:1: D202 No blank lines allowed after function docstring
./util.py:158:1: D202 No blank lines allowed after function docstring
```

> Should we avoid sublime.expand_variables altogether? Or fix it?

I don't know. It has its use cases. And so it's not really broken. For example you can expand the project path `${project_path}/path` which will expand if the current view is part of a project, if its not it will expand to `/path` which is not broken, because it'll work in the context of project.

Expanding user and environment variables fixes the unexpected issues like when a user wants `~/path`, it's pretty clear that they want the user directory expanded. Similarly with environment variables like `${HOME}`. So I think it's ok. It might be useful to some people.

**Comment by kaste** [comment]
❤️ it! 

Sorry for the WS noise here, but we have an explicit ignore here:

https://github.com/SublimeLinter/SublimeLinter-flake8/blob/4dbc888e7023b4a6667e7b453c12cf30befbb6b6/.sublimelinterrc#L7-L9

We should simplify this config. 

@braver LGTM! Can you merge?

**Comment by braver** [comment]
@kaste why shouldn't I just give you access to do that? I'm completely relying on your judgement here anyway.

**Comment by kaste** [comment]
Haha. Yeah, sure. But we ideally have 6 eyes per PR. Two reviewers, and then the user proposing the change.

**Pull request merged**
